### ISSUE TITLE
Swapping grid areas resizes grid item before moving.

### ISSUE THREAD

**Issue by BrianBenninger** [aholachek/animate-css-grid#16]
I am trying to move my item to another grid area, this grid area is larger. The movement animation is working fine, but I am noticing that the item automatically resizes to fit the larger grid area before moving rather than resizing via animation on the way. I am trying to alleviate this with some scaling animation, but the overall item resizing immediately is very frustrating.

Codepen to illustrate:
https://codepen.io/BrianBenninger/pen/JqVgmg

Any thoughts? Am I missing something or is this working as expected?

**Comment by aholachek** [comment]
Hi, animate-css-grid only animates the grid children, it does not animate all elements inside the grid. You can see [in this fork](https://codepen.io/aholachek/pen/pmmREJ) of your pen that the grid children are being animated correctly, but because the images are not set to cover the size of their parents, they are static. A solution would be changing the image styling to respond to the size of its parent container.

**Comment by BrianBenninger** [comment]
Thank you for the information. Closing issue.
