### ISSUE TITLE
Unwrap grid doesn't actually unwrap?

### ISSUE THREAD

**Issue by alexgurr** [aholachek/animate-css-grid#20]
I unwrap the grid, but when I try to rewrap it with wrapGrid I get uncaught exceptions? It looks like the unwrap is only for removing the observers/listeners - it doesn't clear up any state.

**Comment by aholachek** [comment]
Hi, thanks for catching this. I believe it's due to [this line](https://github.com/aholachek/animate-css-grid/blob/master/src/index.ts#L135) which doesn't account for pre-existing data attributes when the grid has been re-wrapped. I will hopefully get a patch release out sometime tomorrow or this weekend.

**Comment by aholachek** [comment]
just released 1.4.1 which should fix this
